version: '3'

services:
  db:
    image: postgres:alpine3.16
    restart: always
    container_name: nest-api-db
    environment:
      POSTGRES_DB: nest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - '35432:5432'
