version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    ## Remember do permission with chmod +x ./.docker/start.sh
    ports: 
     - 3000:3000
    volumes:
     - .:/home/node/app